input bootstrap4, add simple header and footer.
TodoWishlist/TodoWishlist pull request #9
Opened 2017-01-28 04:09 UTC by jason-jz-zhu

1. Finished #1 . 
2. Add simple Header #2 and Footer #3 . Which need to be improved.

2017-01-28 04:51 UTC, QiyuLi requested changes
N/A

2017-01-28 04:53 UTC, QiyuLi requested changes
I think react-bootstrap is not necessary

2017-01-28 04:53 UTC, QiyuLi commented on package.json
> +    "react-bootstrap": "^0.30.7",
Why do we need react-bootstrap?
reactstrap does not need this.

2017-01-28 14:18 UTC, jason-jz-zhu commented on package.json
> +    "react-bootstrap": "^0.30.7",
Yes. I forgot to remove it. I install it just to test. Thanks.

2017-01-29 14:18 UTC, QiyuLi commented
This PR resolve #1 .
See https://help.github.com/articles/closing-issues-via-commit-messages/

2017-01-29 14:36 UTC, QiyuLi requested changes
The top property is not recognized by react

2017-01-29 14:36 UTC, QiyuLi commented on client/modules/App/components/Header/Header.js
> +        <Navbar color="faded" fixed="top" light top toggleable>
Why top here?
The top I'm referring to is the `light top toggleable`

2017-01-30 17:21 UTC, QiyuLi approved these changes

2017-01-30 17:21 UTC, merged